export const defaultAccounts = [
  { code: "1101", accountName: "Cash", category: "Asset", type: "Current Asset", debitRule: "Increases", creditRule: "Decreases", description: "Physical cash" },
  { code: "1102", accountName: "Bank", category: "Asset", type: "Current Asset", debitRule: "Increases", creditRule: "Decreases", description: "Bank Account" },
  { code: "1103", accountName: "Accounts Receivable", category: "Asset", type: "Current Asset", debitRule: "Increases", creditRule: "Decreases", description: "Money owed by customers for transportation or logistics services" },
  { code: "1104", accountName: "Warehousing Facilities", category: "Asset", type: "Fixed Asset", debitRule: "Increases", creditRule: "Decreases", description: "Storage warehouses used in logistics operations" },
  { code: "1105", accountName: "Office Equipment", category: "Asset", type: "Fixed Asset", debitRule: "Increases", creditRule: "Decreases", description: "Office furniture, computers, and administrative equipment" },
  { code: "2101", accountName: "Accounts Payable", category: "Liability", type: "Current Liability", debitRule: "Decreases", creditRule: "Increases", description: "Money owed to suppliers, contractors, or vendors" },
  { code: "2102", accountName: "Taxes Payable", category: "Liability", type: "Current Liability", debitRule: "Decreases", creditRule: "Increases", description: "Taxes owed to government authorities" },
  { code: "2103", accountName: "Wages Payable", category: "Liability", type: "Current Liability", debitRule: "Decreases", creditRule: "Increases", description: "Unpaid salaries and wages owed to drivers and staff" },
  { code: "2201", accountName: "Vehicle Loan Payable", category: "Liability", type: "Non-Current Liability", debitRule: "Decreases", creditRule: "Increases", description: "Long-term loans for purchasing fleet vehicles" },
  { code: "2202", accountName: "Warehouse Mortgage Payable", category: "Liability", type: "Non-Current Liability", debitRule: "Decreases", creditRule: "Increases", description: "Mortgage loans for warehousing facilities" },
  { code: "3101", accountName: "Owner's Equity", category: "Equity", type: "Equity", debitRule: "Decreases", creditRule: "Increases", description: "Owner's initial and additional investments in the business" },
  { code: "3102", accountName: "Retained Earnings", category: "Equity", type: "Equity", debitRule: "Decreases", creditRule: "Increases", description: "Cumulative profits retained in the business for reinvestment" },
  { code: "3103", accountName: "Current Year Earnings", category: "Equity", type: "Equity", debitRule: "Decreases", creditRule: "Increases", description: "Current year's net income or loss" },
  { code: "4101", accountName: "Vendor Expense", category: "Expense", type: "Direct Costs", debitRule: "Increases", creditRule: "Decreases", description: "Expenses paid to vendors for transportation and logistics services" },
  { code: "4102", accountName: "Bank Charges", category: "Expense", type: "Direct Costs", debitRule: "Increases", creditRule: "Decreases", description: "Bank charges for the bank account" },
  { code: "4103", accountName: "Equipments", category: "Expense", type: "Direct Costs", debitRule: "Increases", creditRule: "Decreases", description: "Equipment Costs" },
  { code: "4104", accountName: "Fuel", category: "Expense", type: "Direct Costs", debitRule: "Increases", creditRule: "Decreases", description: "Fuel" },
  { code: "4105", accountName: "Insurance", category: "Expense", type: "Direct Costs", debitRule: "Increases", creditRule: "Decreases", description: "Insurances" },
  { code: "4106", accountName: "Legal and Accounting", category: "Expense", type: "Direct Costs", debitRule: "Increases", creditRule: "Decreases", description: "For Legal Cases" },
  { code: "4107", accountName: "Licsense and Permit", category: "Expense", type: "Direct Costs", debitRule: "Increases", creditRule: "Decreases", description: "Licsense and Permit" },
  { code: "4108", accountName: "Maintenance and Repair", category: "Expense", type: "Direct Costs", debitRule: "Increases", creditRule: "Decreases", description: "Maintenance and Repair" },
  { code: "4109", accountName: "Marketing and Advertising", category: "Expense", type: "Direct Costs", debitRule: "Increases", creditRule: "Decreases", description: "Marketing and Advertising" },
  { code: "4110", accountName: "Office Supplies", category: "Expense", type: "Direct Costs", debitRule: "Increases", creditRule: "Decreases", description: "Supplies for the office" },
  { code: "4111", accountName: "Packaging Material", category: "Expense", type: "Direct Costs", debitRule: "Increases", creditRule: "Decreases", description: "Packaging Material" },
  { code: "4112", accountName: "Petty", category: "Expense", type: "Direct Costs", debitRule: "Increases", creditRule: "Decreases", description: "Small Expenses" },
  { code: "4113", accountName: "Renewals", category: "Expense", type: "Direct Costs", debitRule: "Increases", creditRule: "Decreases", description: "Renewal of Certificates" },
  { code: "4114", accountName: "Rent", category: "Expense", type: "Direct Costs", debitRule: "Increases", creditRule: "Decreases", description: "Rent" },
  { code: "4115", accountName: "Salary and Wages", category: "Expense", type: "Direct Costs", debitRule: "Increases", creditRule: "Decreases", description: "Salary and Wages" },
  { code: "4116", accountName: "Taxes", category: "Expense", type: "Direct Costs", debitRule: "Increases", creditRule: "Decreases", description: "Taxes" },
  { code: "4117", accountName: "Tools", category: "Expense", type: "Direct Costs", debitRule: "Increases", creditRule: "Decreases", description: "Tools" },
  { code: "4118", accountName: "Transportation", category: "Expense", type: "Direct Costs", debitRule: "Increases", creditRule: "Decreases", description: "Transportation" },
  { code: "4119", accountName: "Utilities", category: "Expense", type: "Direct Costs", debitRule: "Increases", creditRule: "Decreases", description: "Utlities" },
  { code: "5101", accountName: "Logistics Services Revenue", category: "Revenue", type: "Revenue", debitRule: "Decreases", creditRule: "Increases", description: "Revenue earned from logistics services" },
  { code: "5102", accountName: "Packaging Revenue", category: "Revenue", type: "Revenue", debitRule: "Decreases", creditRule: "Increases", description: "Revenue earned from Packaging" },
  { code: "5103", accountName: "Other Revenue", category: "Revenue", type: "Revenue", debitRule: "Decreases", creditRule: "Increases", description: "Revenue earned from third parties" },
];
